apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-lab
  region: us-east-1
  version: "1.33"

iam:
  withOIDC: true

managedNodeGroups:
  - name: workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 20
    privateNetworking: false
    amiFamily: AmazonLinux2023

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent