apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-html

data:
  index.php: |
    <?php
    echo "<h1>Hello from Kubernetes on Amazon EKS!</h1>";
    echo "<p>Pod: " . gethostname() . "</p>";
    echo "<p>Time: " . date('Y-m-d H:i:s') . "</p>";
    ?>