apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-html

data:
  index.php: |
    <?php

    if ($_SERVER['REQUEST_URI'] == '/stress') {

        $start = microtime(true);

        while (microtime(true) - $start < 5) {
            sqrt(rand());
        }

        echo "CPU stress completed on pod: " . gethostname();
        exit;
    }

    echo "<h1>Hello from Amazon EKS</h1>";
    echo "<p>Pod: " . gethostname() . "</p>";
    ?>